version: '3.8'

volumes:
  mongodb:

services:
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    restart: always
    environment:
      MONGO_INITDB_DATABASE: sampleDB
    ports:
      - 27017:27017
    volumes:
      - mongodb://data/db

  bot:
    image: berg1005/agregate_tg_bot_testtask_rlt:latest
    env_file: .env
    command: python ./main.py
    depends_on:
      - mongodb